# Generated by Django 5.0.6 on 2024-06-24 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applogin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
