# Generated by Django 5.0.6 on 2024-06-25 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogin', '0002_delete_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='descripcion',
            field=models.TextField(default='Descripción por defecto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(default='Descripción por defecto'),
            preserve_default=False,
        ),
    ]
