# Generated by Django 5.0.6 on 2024-06-25 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogin', '0003_documento_descripcion_proyecto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='descripcion',
            field=models.TextField(default='Descripción predeterminada'),
        ),
    ]
