# Generated by Django 5.0.6 on 2024-06-25 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogin', '0004_alter_documento_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelacionDocumento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones', to='applogin.documento')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones', to='applogin.fase')),
            ],
        ),
    ]
